services:
  - type: web
    name: projeto-restaurante
    env: python
    buildCommand: "./build.sh"
    
    # --- CORREÇÃO AQUI ---
    # --chdir entra na pasta 'projetorestaurante' (onde está o manage.py)
    # e então procura por 'restaurante.wsgi' (que está em 'restaurante/wsgi.py')
    startCommand: "gunicorn --chdir projetorestaurante restaurante.wsgi:application"
    
    plan: free

    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: restaurante-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4

databases:
  - name: restaurante-db
    plan: free