services:
  - type: web
    name: projeto-restaurante
    env: python
    buildCommand: "./build.sh"
    
    # --chdir diz ao Gunicorn para entrar na pasta 'projetorestaurante'
    # antes de procurar o 'restaurante.wsgi'
    startCommand: "gunicorn --chdir projetorestaurante restaurante.wsgi:application"
    
    plan: free

    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: restaurante-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4

databases:
  - name: restaurante-db
    plan: free