services:
  - type: web
    name: projeto-restaurante
    env: python
    buildCommand: "./build.sh"
    
    # --- CORREÇÃO AQUI ---
    # O --chdir (change directory) diz ao Gunicorn para rodar A PARTIR
    # da pasta que contém o seu wsgi.py (restaurante/wsgi.py)
    startCommand: "gunicorn --chdir projetorestaurante/projetorestaurante restaurante.wsgi:application"
    # --- FIM DA CORREÇÃO ---

    plan: free

    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: restaurante-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4

databases:
  - name: restaurante-db
    plan: free